FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /src

COPY Dependencies.props /Dependencies.props
COPY Directory.Build.props /Directory.Build.props

COPY src/NotificationService.Migrations.PostgreSql/ NotificationService.Migrations.PostgreSql/

WORKDIR /src/NotificationService.Migrations.PostgreSql
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /src

COPY --from=build-env /src/WelwiseGames.NotificationService.Migrations.PostgreSql/out .

ENTRYPOINT ["dotnet", "WelwiseGames.NotificationService.Migrations.PostgreSql.dll"]